#!/bin/bash
################################################################################
# Bootstrap GitHub Actions OIDC IAM Role
# Generated by Opsera Code-to-Cloud v0.6
#
# This script creates the initial IAM role that allows GitHub Actions to
# authenticate with AWS using OIDC (no access keys required).
#
# Prerequisites:
#   - AWS CLI configured with admin credentials (one-time setup)
#   - jq installed
#
# Usage:
#   ./bootstrap-iam-role.sh
#
# After running this script, GitHub Actions can use OIDC authentication.
################################################################################

set -euo pipefail

# Configuration
AWS_REGION="${AWS_REGION:-us-west-2}"
APP_NAME="voting2"
ENVIRONMENT="dev"
GITHUB_ORG="${GITHUB_ORG:-opsera-ai}"
GITHUB_REPO="${GITHUB_REPO:-enterprise-voting-app-t1}"

# Derived values
ROLE_NAME="${APP_NAME}-${ENVIRONMENT}-github-actions"
POLICY_NAME="${APP_NAME}-${ENVIRONMENT}-github-actions-bootstrap"

echo "============================================================"
echo "Bootstrap GitHub Actions OIDC Role"
echo "============================================================"
echo "AWS Region:    ${AWS_REGION}"
echo "App Name:      ${APP_NAME}"
echo "Environment:   ${ENVIRONMENT}"
echo "GitHub Org:    ${GITHUB_ORG}"
echo "GitHub Repo:   ${GITHUB_REPO}"
echo "Role Name:     ${ROLE_NAME}"
echo "============================================================"

# Get AWS Account ID
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "AWS Account:   ${AWS_ACCOUNT_ID}"
echo ""

# Check if GitHub OIDC provider exists
echo "Checking for existing GitHub OIDC provider..."
OIDC_PROVIDER_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/token.actions.githubusercontent.com"

if aws iam get-open-id-connect-provider --open-id-connect-provider-arn "$OIDC_PROVIDER_ARN" 2>/dev/null; then
    echo "GitHub OIDC provider already exists"
else
    echo "Creating GitHub OIDC provider..."
    aws iam create-open-id-connect-provider \
        --url "https://token.actions.githubusercontent.com" \
        --client-id-list "sts.amazonaws.com" \
        --thumbprint-list "6938fd4d98bab03faadb97b34396831e3780aea1" "1c58a3a8518e8759bf075b76b750d4f2df264fcd"
    echo "GitHub OIDC provider created"
fi

# Create trust policy
echo ""
echo "Creating trust policy..."
TRUST_POLICY=$(cat <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "${OIDC_PROVIDER_ARN}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:${GITHUB_ORG}/${GITHUB_REPO}:*"
                }
            }
        }
    ]
}
EOF
)

# Check if role exists
echo "Checking for existing role..."
if aws iam get-role --role-name "$ROLE_NAME" 2>/dev/null; then
    echo "Role ${ROLE_NAME} already exists, updating trust policy..."
    aws iam update-assume-role-policy \
        --role-name "$ROLE_NAME" \
        --policy-document "$TRUST_POLICY"
else
    echo "Creating role ${ROLE_NAME}..."
    aws iam create-role \
        --role-name "$ROLE_NAME" \
        --assume-role-policy-document "$TRUST_POLICY" \
        --tags Key=Application,Value="${APP_NAME}" Key=Environment,Value="${ENVIRONMENT}" Key=ManagedBy,Value="bootstrap-script"
fi

# Create bootstrap policy (enough to run Terraform)
echo ""
echo "Creating bootstrap policy..."
BOOTSTRAP_POLICY=$(cat <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ECRManagement",
            "Effect": "Allow",
            "Action": [
                "ecr:*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "RDSManagement",
            "Effect": "Allow",
            "Action": [
                "rds:*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "ElastiCacheManagement",
            "Effect": "Allow",
            "Action": [
                "elasticache:*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "IAMRoleManagement",
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:GetRole",
                "iam:ListRoles",
                "iam:UpdateRole",
                "iam:TagRole",
                "iam:UntagRole",
                "iam:PassRole",
                "iam:AttachRolePolicy",
                "iam:DetachRolePolicy",
                "iam:ListAttachedRolePolicies",
                "iam:ListRolePolicies",
                "iam:CreatePolicy",
                "iam:DeletePolicy",
                "iam:GetPolicy",
                "iam:GetPolicyVersion",
                "iam:ListPolicies",
                "iam:ListPolicyVersions",
                "iam:CreatePolicyVersion",
                "iam:DeletePolicyVersion",
                "iam:CreateOpenIDConnectProvider",
                "iam:GetOpenIDConnectProvider",
                "iam:DeleteOpenIDConnectProvider",
                "iam:ListOpenIDConnectProviders"
            ],
            "Resource": "*"
        },
        {
            "Sid": "EC2Networking",
            "Effect": "Allow",
            "Action": [
                "ec2:Describe*",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:CreateTags",
                "ec2:DeleteTags"
            ],
            "Resource": "*"
        },
        {
            "Sid": "EKSAccess",
            "Effect": "Allow",
            "Action": [
                "eks:DescribeCluster",
                "eks:ListClusters",
                "eks:AccessKubernetesApi"
            ],
            "Resource": "*"
        },
        {
            "Sid": "SecretsManager",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecrets"
            ],
            "Resource": "*"
        },
        {
            "Sid": "TerraformState",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::opsera-terraform-state-usw2",
                "arn:aws:s3:::opsera-terraform-state-usw2/*"
            ]
        },
        {
            "Sid": "TerraformLocks",
            "Effect": "Allow",
            "Action": [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:DeleteItem"
            ],
            "Resource": "arn:aws:dynamodb:${AWS_REGION}:${AWS_ACCOUNT_ID}:table/terraform-locks"
        }
    ]
}
EOF
)

# Check if policy exists
POLICY_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:policy/${POLICY_NAME}"
if aws iam get-policy --policy-arn "$POLICY_ARN" 2>/dev/null; then
    echo "Policy ${POLICY_NAME} already exists, creating new version..."
    # Delete oldest version if we're at the limit
    VERSIONS=$(aws iam list-policy-versions --policy-arn "$POLICY_ARN" --query 'Versions[?IsDefaultVersion==`false`].VersionId' --output text)
    for VERSION in $VERSIONS; do
        aws iam delete-policy-version --policy-arn "$POLICY_ARN" --version-id "$VERSION" 2>/dev/null || true
    done
    aws iam create-policy-version \
        --policy-arn "$POLICY_ARN" \
        --policy-document "$BOOTSTRAP_POLICY" \
        --set-as-default
else
    echo "Creating policy ${POLICY_NAME}..."
    aws iam create-policy \
        --policy-name "$POLICY_NAME" \
        --policy-document "$BOOTSTRAP_POLICY" \
        --tags Key=Application,Value="${APP_NAME}" Key=Environment,Value="${ENVIRONMENT}"
fi

# Attach policy to role
echo ""
echo "Attaching policy to role..."
aws iam attach-role-policy \
    --role-name "$ROLE_NAME" \
    --policy-arn "$POLICY_ARN" 2>/dev/null || echo "Policy already attached"

# Print summary
echo ""
echo "============================================================"
echo "Bootstrap Complete!"
echo "============================================================"
echo ""
echo "Role ARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${ROLE_NAME}"
echo ""
echo "Next Steps:"
echo "1. Add this secret to your GitHub repository:"
echo "   Secret Name: AWS_ACCOUNT_ID"
echo "   Secret Value: ${AWS_ACCOUNT_ID}"
echo ""
echo "2. Run the '00-Bootstrap Infrastructure' workflow with action: apply"
echo ""
echo "3. After Terraform runs, it will create the full IRSA roles and policies"
echo ""
echo "============================================================"
