#!/bin/bash
################################################################################
# Setup Terraform Backend (S3 + DynamoDB)
# Generated by Opsera Code-to-Cloud v0.6
#
# This script creates the S3 bucket and DynamoDB table required for
# Terraform state management.
#
# Prerequisites:
#   - AWS CLI configured with admin credentials
#
# Usage:
#   ./setup-terraform-backend.sh
#
# This is a one-time setup per AWS account/region.
################################################################################

set -euo pipefail

# Configuration
AWS_REGION="${AWS_REGION:-us-west-2}"
BUCKET_NAME="opsera-terraform-state-usw2"
DYNAMODB_TABLE="terraform-locks"

echo "============================================================"
echo "Setup Terraform Backend"
echo "============================================================"
echo "AWS Region:     ${AWS_REGION}"
echo "S3 Bucket:      ${BUCKET_NAME}"
echo "DynamoDB Table: ${DYNAMODB_TABLE}"
echo "============================================================"

# Get AWS Account ID
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "AWS Account:    ${AWS_ACCOUNT_ID}"
echo ""

# Create S3 bucket
echo "Checking S3 bucket..."
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
    echo "S3 bucket ${BUCKET_NAME} already exists"
else
    echo "Creating S3 bucket ${BUCKET_NAME}..."

    # Create bucket (different syntax for us-east-1)
    if [ "$AWS_REGION" = "us-east-1" ]; then
        aws s3api create-bucket \
            --bucket "$BUCKET_NAME" \
            --region "$AWS_REGION"
    else
        aws s3api create-bucket \
            --bucket "$BUCKET_NAME" \
            --region "$AWS_REGION" \
            --create-bucket-configuration LocationConstraint="$AWS_REGION"
    fi

    # Enable versioning
    echo "Enabling versioning..."
    aws s3api put-bucket-versioning \
        --bucket "$BUCKET_NAME" \
        --versioning-configuration Status=Enabled

    # Enable encryption
    echo "Enabling encryption..."
    aws s3api put-bucket-encryption \
        --bucket "$BUCKET_NAME" \
        --server-side-encryption-configuration '{
            "Rules": [
                {
                    "ApplyServerSideEncryptionByDefault": {
                        "SSEAlgorithm": "AES256"
                    },
                    "BucketKeyEnabled": true
                }
            ]
        }'

    # Block public access
    echo "Blocking public access..."
    aws s3api put-public-access-block \
        --bucket "$BUCKET_NAME" \
        --public-access-block-configuration '{
            "BlockPublicAcls": true,
            "IgnorePublicAcls": true,
            "BlockPublicPolicy": true,
            "RestrictPublicBuckets": true
        }'

    # Add tags
    echo "Adding tags..."
    aws s3api put-bucket-tagging \
        --bucket "$BUCKET_NAME" \
        --tagging '{
            "TagSet": [
                {"Key": "Purpose", "Value": "terraform-state"},
                {"Key": "ManagedBy", "Value": "bootstrap-script"}
            ]
        }'

    echo "S3 bucket created successfully"
fi

# Create DynamoDB table
echo ""
echo "Checking DynamoDB table..."
if aws dynamodb describe-table --table-name "$DYNAMODB_TABLE" --region "$AWS_REGION" 2>/dev/null; then
    echo "DynamoDB table ${DYNAMODB_TABLE} already exists"
else
    echo "Creating DynamoDB table ${DYNAMODB_TABLE}..."
    aws dynamodb create-table \
        --table-name "$DYNAMODB_TABLE" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "$AWS_REGION" \
        --tags Key=Purpose,Value=terraform-locks Key=ManagedBy,Value=bootstrap-script

    echo "Waiting for table to become active..."
    aws dynamodb wait table-exists --table-name "$DYNAMODB_TABLE" --region "$AWS_REGION"
    echo "DynamoDB table created successfully"
fi

# Print summary
echo ""
echo "============================================================"
echo "Terraform Backend Setup Complete!"
echo "============================================================"
echo ""
echo "S3 Bucket:      s3://${BUCKET_NAME}"
echo "DynamoDB Table: ${DYNAMODB_TABLE}"
echo ""
echo "Terraform backend configuration:"
echo ""
echo '  backend "s3" {'
echo "    bucket         = \"${BUCKET_NAME}\""
echo '    key            = "voting2/dev/terraform.tfstate"'
echo "    region         = \"${AWS_REGION}\""
echo "    encrypt        = true"
echo "    dynamodb_table = \"${DYNAMODB_TABLE}\""
echo '  }'
echo ""
echo "============================================================"
